export const nameOrigin: string[] = [
    'No Preference',
    'English',
    'Spanish',
    'French',
    'German',
    'Italian',
    'Portuguese',
    'Irish',
    'Indian',
    'Japanese',
    'Korean',
    'Chinese',
    'Arabic',
    'Russian',
    'Hebrew',
];

export const meanAndTheme: string[] = [
    'No preference',
    'Nature',
    'Strength',
    'Love',
    'Virtue',
    'Luck',
    'Happiness',
    'Courage',
    'Wisdom',
    'Beauty',
    'Peace',
    'Mythical',
    'Artistic',
    'Historic',
    'Spiritual',
    'Other',
]